# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update README with Latest Velog Posts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests

    - name: Update README
      run: python update_readme_with_blog_posts.py

    - name: Commit changes
      run: |
        git config --local user.email "freesky111@naver.com"
        git config --local user.name "freeskyES"
        git add README.md
        git commit -m "Update README with latest blog posts"
        git push
