name: Update README with Latest Velog Posts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests

    - name: Update README
      run: python update_readme_with_blog_posts.py

    - name: Commit changes
      run: |
        git config --local user.email "freesky111@naver.com"
        git config --local user.name "freeskyES"
        git stash                          # 변경 사항 임시 저장
        git pull origin main --rebase      # 원격 변경 사항 병합
        git stash pop || true              # 임시 저장 복원

        # 변경 사항 확인
        if git diff --quiet && git diff --cached --quiet; then
          echo "No changes to commit. Skipping push."
        else
          git add README.md posts_cache.txt
          git commit -m "Update README and cache with latest blog posts"
          git push
        fi
